import {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
import {signInWithPhoneNumber, RecaptchaVerifier} from "firebase/auth";
import {auth} from "../firebase/firebaseApp";

export default function Home() {

    const [phoneNumber, setPhoneNumber] = useState('')
    const [confirmation, setConfirmation] = useState(null)

    const [otp, setOTP] = useState('')

    function setupRecaptcha(number) {

        // const recaptchaVerifier =  new RecaptchaVerifier('sign-in-button', {
        //     'size': 'invisible',
        //     'callback': (response) => {
        //         // reCAPTCHA solved, allow signInWithPhoneNumber.
        //         return signInWithPhoneNumber(auth, phoneNumber, recaptchaVerifier)
        //     }
        // }, auth);
        const recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {},
            auth)
        recaptchaVerifier.render()
        return signInWithPhoneNumber(auth, '+91' + number, recaptchaVerifier)
    }

    async function handleGetOTP() {
        const resp = await setupRecaptcha(phoneNumber)
        setConfirmation(resp)
    }

    async function handleVerifyOTP() {
        const resp = await confirmation.confirm(otp)
        console.log(resp)
    }


    return (
        <div className={"container"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={"main"}>
                <div>
                    <label>Phone Number</label>
                    <input type={"tel"} value={phoneNumber} onChange={e => setPhoneNumber(e.target.value)}/>
                    <button onClick={handleGetOTP}>Get OTP</button>
                </div>
                <div id={"recaptcha-container"}/>
                <div>
                    <label>OTP</label>
                    <input type={"number"} value={otp} onChange={e => setOTP(e.target.value)}/>
                    <button onClick={handleVerifyOTP}>Verify OTP</button>
                </div>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
            </main>
        </div>
    )
}
