import {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {signInWithPhoneNumber, RecaptchaVerifier} from "firebase/auth";
import {auth} from "../firebase/firebaseApp";

export default function Home() {

    const [phoneNumber, setPhoneNumber] = useState('')
    const [confirmation, setConfirmation] = useState(null)

    const [otp, setOTP] = useState('')

    function setupRecaptcha(number) {

        // const recaptchaVerifier =  new RecaptchaVerifier('sign-in-button', {
        //     'size': 'invisible',
        //     'callback': (response) => {
        //         // reCAPTCHA solved, allow signInWithPhoneNumber.
        //         return signInWithPhoneNumber(auth, phoneNumber, recaptchaVerifier)
        //     }
        // }, auth);
        const recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {},
            auth)
        recaptchaVerifier.render()
        return signInWithPhoneNumber(auth, '+91' + number, recaptchaVerifier)
    }

    async function handleGetOTP() {
        const resp = await setupRecaptcha(phoneNumber)
        setConfirmation(resp)
    }

    async function handleVerifyOTP() {
        const resp = await confirmation.confirm(otp)
        console.log(resp)

    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <label>Phone Number
                    <input type={"tel"} value={phoneNumber} onChange={e => setPhoneNumber(e.target.value)}/>
                </label>
                <div id={"recaptcha-container"}/>
                <button onClick={handleGetOTP}>Get OTP</button>
                <label>OTP
                    <input type={"number"} value={otp} onChange={e => setOTP(e.target.value)}/>
                </label>

                <button onClick={handleVerifyOTP}>Verify OTP</button>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
